### ISSUE TITLE
Only saving the spine

### ISSUE THREAD

**Issue by clk394** [acestronautical/bookcover-js#8]
Hi!
The spine is the only bit saving when I download it

**Comment by acestronautical** [comment]
Hmm, I'm not having that issue. Could you provide me with some more information about your browser and system and what files you were using?

If possible could you right click and select 'inspect' on the browser page and see if there are any errors when you click to save?

When you click "Save Covers" you should end up with three separate files: spine_cover.svg, back_cover.svg, and front_cover.svg

**Comment by clk394** [comment]
Hi! 
Sure, it's probably my fault. I have a MacBook Pro from 2020 updated to the latest software version. I used Safari for this. 
I just imported a svg of mechanical gears design


<img width="341" alt="Screenshot 2024-02-17 at 12 32 07 PM" src="https://github.com/acestronautical/bookcover-js/assets/160284174/7d48d90b-1de2-4cd9-8a94-8bd884ac0469">

I've attached what the download looks like when I select save covers. 

I don't know how to check for errors but going through it, it doesn't seem to be showing any
<img width="960" alt="Screenshot 2024-02-17 at 12 38 01 PM" src="https://github.com/acestronautical/bookcover-js/assets/160284174/2208f76e-bbce-4138-a9c5-416b093d925f">

**Comment by acestronautical** [comment]
Can you attach the mechanical gears SVG? It might be something specific to that file.

Edit: Actually this is definitely a safari browser compatibility issue.

**Comment by acestronautical** [comment]
I just pushed some changes which should fix this, can you try again?

**Comment by clk394** [comment]
Hi! 

It worked! It's saving as a zip now with everything

Thank you!

**Comment by acestronautical** [comment]
yeah safari doesn't support downloading multiple files at once for some reason, so the easiest solution was to just zip everything before download. Glad its working for you now!
